version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb-replica
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-replica.js:/docker-entrypoint-initdb.d/init-replica.js:ro
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

volumes:
  mongodb_data: